# Generated by Django 5.2.7 on 2025-10-25 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userblocktest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='content.lesson'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.word'),
        ),
        migrations.AlterUniqueTogether(
            name='userblocktest',
            unique_together={('user', 'block_test')},
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'word')},
        ),
    ]
